schema-version = "1.13.0"

[install]
nodejs.pkg-path = "nodejs"
gum.pkg-path = "gum"

[vars]
INTRO_MESSAGE = '''
Start Dev server:
  $ flox services start dev

Dev server URL:
  http://localhost:3000/'''

[hook]
on-activate = """
  npm install
"""

[profile]
common = '''
  gum style \
  --foreground 212 --border-foreground 212 --border double \
  --align left --width 40 --margin "1 1" --padding "1 1" \
    $INTRO_MESSAGE
'''

[services]
dev.command = "npm run dev"
