import type { TeamDataEntry } from '@/app/types/team';

const teamData: TeamDataEntry[] = [
  {
    name: 'Anaheim Ducks',
    slug: 'ducks',
    hashtag: 'FlyTogether',
    abbreviation: 'ANA',
    teamColor: '#cf4520',
    secondaryTeamColor: '#89734c',
    teamId: 24,
    division: 'Pacific',
  },
  {
    name: 'Boston Bruins',
    slug: 'bruins',
    hashtag: 'NHLBruins',
    abbreviation: 'BOS',
    teamColor: '#FFB81C',
    secondaryTeamColor: '#000000',
    teamId: 6,
    division: 'Atlantic',
  },
  {
    name: 'Buffalo Sabres',
    slug: 'sabres',
    hashtag: 'SabreHood',
    abbreviation: 'BUF',
    teamColor: '#003087',
    secondaryTeamColor: '#FFB81C',
    teamId: 7,
    division: 'Atlantic',
  },
  {
    name: 'Calgary Flames',
    slug: 'flames',
    hashtag: 'Flames',
    abbreviation: 'CGY',
    teamColor: '#c8102e',
    secondaryTeamColor: '#FAAF19',
    teamId: 20,
    division: 'Pacific',
  },
  {
    name: 'Carolina Hurricanes',
    slug: 'hurricanes',
    hashtag: 'RaiseUp',
    abbreviation: 'CAR',
    teamColor: '#c8102e',
    secondaryTeamColor: '#FFFFFF',
    teamId: 12,
    division: 'Metropolitan',
  },
  {
    name: 'Chicago Blackhawks',
    slug: 'blackhawks',
    hashtag: 'Blackhawks',
    abbreviation: 'CHI',
    teamColor: '#ce1126',
    secondaryTeamColor: '#FF671B',
    teamId: 16,
    division: 'Central',
  },
  {
    name: 'Colorado Avalanche',
    slug: 'avalanche',
    hashtag: 'GoAvsGo',
    abbreviation: 'COL',
    teamColor: '#8a2432',
    secondaryTeamColor: '#236192',
    teamId: 21,
    division: 'Central',
  },
  {
    name: 'Columbus Blue Jackets',
    slug: 'bluejackets',
    hashtag: 'CBJ',
    abbreviation: 'CBJ',
    teamColor: '#041e42',
    secondaryTeamColor: '#ce1126',
    teamId: 29,
    division: 'Metropolitan',
  },
  {
    name: 'Dallas Stars',
    slug: 'stars',
    hashtag: 'TexasHockey',
    abbreviation: 'DAL',
    teamColor: '#00823e',
    secondaryTeamColor: '#8F8F8C',
    teamId: 25,
    division: 'Central',
  },
  {
    name: 'Detroit Red Wings',
    slug: 'redwings',
    hashtag: 'LGRW',
    abbreviation: 'DET',
    teamColor: '#c8102e',
    secondaryTeamColor: '#FFFFFF',
    teamId: 17,
    division: 'Atlantic',
  },
  {
    name: 'Edmonton Oilers',
    slug: 'oilers',
    hashtag: 'LetsGoOilers',
    abbreviation: 'EDM',
    teamColor: '#00205b',
    secondaryTeamColor: '#FF4C00',
    teamId: 22,
    division: 'Pacific',
  },
  {
    name: 'Florida Panthers',
    slug: 'panthers',
    hashtag: 'TimeToHunt',
    abbreviation: 'FLA',
    teamColor: '#041E42',
    secondaryTeamColor: '#c8102E',
    teamId: 13,
    division: 'Atlantic',
  },
  {
    name: 'Los Angeles Kings',
    slug: 'kings',
    hashtag: 'GoKingsGo',
    abbreviation: 'LAK',
    teamColor: '#8a9599',
    secondaryTeamColor: '#111111',
    teamId: 26,
    division: 'Pacific',
  },
  {
    name: 'Minnesota Wild',
    slug: 'wild',
    hashtag: 'MNWild',
    abbreviation: 'MIN',
    teamColor: '#0e4431',
    secondaryTeamColor: '#ddc9a3',
    teamId: 30,
    division: 'Central',
  },
  {
    name: 'Montréal Canadiens',
    slug: 'canadiens',
    hashtag: 'GoHabsGo',
    abbreviation: 'MTL',
    teamColor: '#a6192e',
    secondaryTeamColor: '#192168',
    teamId: 8,
    division: 'Atlantic',
  },
  {
    name: 'Nashville Predators',
    slug: 'predators',
    hashtag: 'Smashville',
    abbreviation: 'NSH',
    teamColor: '#ffb81c',
    secondaryTeamColor: '#041E42',
    teamId: 18,
    division: 'Central',
  },
  {
    name: 'New Jersey Devils',
    slug: 'devils',
    hashtag: 'NJDevils',
    abbreviation: 'NJD',
    teamColor: '#cc0000',
    secondaryTeamColor: '#000000',
    teamId: 1,
    division: 'Metropolitan',
  },
  {
    name: 'New York Islanders',
    slug: 'islanders',
    hashtag: 'Isles',
    abbreviation: 'NYI',
    teamColor: '#00468b',
    secondaryTeamColor: '#f47d30',
    teamId: 2,
    division: 'Metropolitan',
  },
  {
    name: 'New York Rangers',
    slug: 'rangers',
    hashtag: 'NYR',
    abbreviation: 'NYR',
    teamColor: '#0033a0',
    secondaryTeamColor: '#CE1126',
    teamId: 3,
    division: 'Metropolitan',
  },
  {
    name: 'Ottawa Senators',
    hashtag: 'GoSensGo',
    abbreviation: 'OTT',
    teamColor: '#c8102e',
    secondaryTeamColor: '#000000',
    teamId: 9,
    division: 'Atlantic',
  },
  {
    name: 'Philadelphia Flyers',
    slug: 'flyers',
    hashtag: 'LetsGoFlyers',
    abbreviation: 'PHI',
    teamColor: '#d24303',
    secondaryTeamColor: '#000000',
    teamId: 4,
    division: 'Metropolitan',
  },
  {
    name: 'Pittsburgh Penguins',
    slug: 'penguins',
    hashtag: 'LetsGoPens',
    abbreviation: 'PIT',
    teamColor: '#000000',
    secondaryTeamColor: '#CFC493',
    teamId: 5,
    division: 'Metropolitan',
  },
  {
    name: 'St. Louis Blues',
    slug: 'blues',
    hashtag: 'STLBlues',
    abbreviation: 'STL',
    teamColor: '#004986',
    secondaryTeamColor: '#FCB514',
    teamId: 19,
    division: 'Central',
  },
  {
    name: 'San Jose Sharks',
    slug: 'sharks',
    hashtag: 'TheFutureIsTeal',
    abbreviation: 'SJS',
    teamColor: '#00778b',
    secondaryTeamColor: '#e57200',
    teamId: 28,
    division: 'Pacific',
  },
  {
    name: 'Seattle Kraken',
    slug: 'kraken',
    hashtag: 'SeaKraken',
    abbreviation: 'SEA',
    teamColor: '#001425',
    secondaryTeamColor: '#99d9d9',
    teamId: 55,
    division: 'Pacific',
  },
  {
    name: 'Tampa Bay Lightning',
    slug: 'lightning',
    hashtag: 'GoBolts',
    abbreviation: 'TBL',
    teamColor: '#00205b',
    secondaryTeamColor: '#000',
    teamId: 14,
    division: 'Atlantic',
  },
  {
    name: 'Toronto Maple Leafs',
    slug: 'mapleleafs',
    hashtag: 'LeafsForever',
    abbreviation: 'TOR',
    teamColor: '#00205b',
    secondaryTeamColor: '#FFFFFF',
    teamId: 10,
    division: 'Atlantic',
  },
  {
    name: 'Utah Mammoth',
    slug: 'utah',
    hashtag: 'TusksUp',
    abbreviation: 'UTA',
    teamColor: '#6cace4',
    secondaryTeamColor: '#010101',
    teamId: 68,
    division: 'Central',
  },
  {
    name: 'Vancouver Canucks',
    slug: 'canucks',
    hashtag: 'Canucks',
    abbreviation: 'VAN',
    teamColor: '#00205b',
    secondaryTeamColor: '#00843d',
    teamId: 23,
    division: 'Pacific',
  },
  {
    name: 'Vegas Golden Knights',
    slug: 'goldenknights',
    hashtag: 'VegasBorn',
    abbreviation: 'VGK',
    teamColor: '#b9975b',
    secondaryTeamColor: '#333f48',
    teamId: 54,
    division: 'Pacific',
  },
  {
    name: 'Washington Capitals',
    slug: 'capitals',
    hashtag: 'ALLCAPS',
    abbreviation: 'WSH',
    teamColor: '#041E42',
    secondaryTeamColor: '#C8102E',
    teamId: 15,
    division: 'Metropolitan',
  },
  {
    name: 'Winnipeg Jets',
    slug: 'jets',
    hashtag: 'GoJetsGo',
    abbreviation: 'WPG',
    teamColor: '#041e42',
    secondaryTeamColor: '#296ec8',
    teamId: 52,
    division: 'Central',
  },
  // International
  {
    name: 'Canada',
    abbreviation: 'CAN',
    teamColor: '#c8102e',
    secondaryTeamColor: '#ddcba4',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Finland',
    abbreviation: 'FIN',
    teamColor: '#041e42',
    secondaryTeamColor: '#ffb81c',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Sweden',
    abbreviation: 'SWE',
    teamColor: '#006eb3',
    secondaryTeamColor: '#041e42',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'United States',
    abbreviation: 'USA',
    teamColor: '#003087',
    secondaryTeamColor: '#c8102e',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Czechia',
    abbreviation: 'CZE',
    teamColor: '#11457e', // blue
    secondaryTeamColor: '#d7141a',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Switzerland',
    abbreviation: 'SUI',
    teamColor: '#d52b1e',
    secondaryTeamColor: '#ffffff',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Germany',
    abbreviation: 'GER',
    teamColor: '#000000',
    secondaryTeamColor: '#dd0000',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Slovakia',
    abbreviation: 'SVK',
    teamColor: '#0b4ea2',
    secondaryTeamColor: '#ee1c25',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Latvia',
    abbreviation: 'LAT',
    teamColor: '#9e3039',
    secondaryTeamColor: '#ffffff',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Denmark',
    abbreviation: 'DEN',
    teamColor: '#c60c30',
    secondaryTeamColor: '#ffffff',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Italy',
    abbreviation: 'ITA',
    teamColor: '#008c45',
    secondaryTeamColor: '#cd212a',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Slovakia',
    abbreviation: 'SVK',
    teamColor: '#254AA5',
    secondaryTeamColor: '#ED1C24',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Latvia',
    abbreviation: 'LAT',
    teamColor: '#9D2235',
    secondaryTeamColor: '#FFFFFF',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'France',
    abbreviation: 'FRA',
    teamColor: '#0055A4',
    secondaryTeamColor: '#EF4135',
    teamId: 9999999,
    division: 'International',
  },
  {
    name: 'Japan',
    abbreviation: 'JPN',
    teamColor: '#BC002D',
    secondaryTeamColor: '#FFFFFF',
    teamId: 9999999,
    division: 'International',
  },
  // Legacy Teams
  {
    name: 'Detroit Cougars',
    teamColor: '#000000',
    secondaryTeamColor: '#FFFFFF',
    abbreviation: 'DCG',
    teamId: 40,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/DCG_19261927-19291930_dark.svg',
  },
  {
    name: 'Detroit Falcons',
    teamColor: '#000000',
    secondaryTeamColor: '#FFFFFF',
    abbreviation: 'DFL',
    teamId: 50,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/DFL_19301931-19311932_dark.svg',
  },
  {
    name: 'St. Louis Eagles',
    teamColor: '#A6192E',
    secondaryTeamColor: '#0033A0',
    abbreviation: 'SLE',
    teamId: 45,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/SLE_19341935_dark.svg',
  },
  {
    name: 'Kansas City Scouts',
    teamColor: '#0038A8',
    secondaryTeamColor: '#CE1126',
    abbreviation: 'KCS',
    teamId: 48,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/KCS_19741975-19751976_dark.svg',
  },
  {
    name: 'Oakland Seals',
    teamColor: '#0038A8',
    secondaryTeamColor: '#FFFFFF',
    abbreviation: 'OAK',
    teamId: 46,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/OAK_19671968-19691970_dark.svg',
  },
  {
    name: 'California Golden Seals',
    teamColor: '#0038A8',
    secondaryTeamColor: '#FFB81C',
    abbreviation: 'CGS',
    teamId: 56,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/CGS_19701971-19731974_dark.svg',
  },
  {
    name: 'Atlanta Flames',
    teamColor: '#CE1126',
    secondaryTeamColor: '#FFB81C',
    abbreviation: 'AFM',
    teamId: 47,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/AFM_19721973-19791980_dark.svg',
  },
  {
    name: 'Winnipeg Jets (1979)',
    teamColor: '#004C97',
    secondaryTeamColor: '#FFFFFF',
    abbreviation: 'WIN',
    teamId: 33,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/WIN_19901991-19951996_dark.svg',
  },
  {
    name: 'Phoenix Coyotes',
    teamColor: '#8C2633',
    secondaryTeamColor: '#000000',
    abbreviation: 'PHX',
    teamId: 27,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/PHX_20032004-20132014_dark.svg',
  },
  {
    name: 'Colorado Rockies',
    teamColor: '#0038A8',
    secondaryTeamColor: '#CE1126',
    abbreviation: 'CLR',
    teamId: 35,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/CLR_19761977-19811982_dark.svg',
  },
  {
    name: 'Quebec Nordiques',
    teamColor: '#005EB8',
    secondaryTeamColor: '#DA291C',
    abbreviation: 'QUE',
    teamId: 32,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/QUE_19791980-19941995_dark.svg',
  },
  {
    name: 'Hartford Whalers',
    teamColor: '#00205B',
    secondaryTeamColor: '#046A38',
    abbreviation: 'HFD',
    teamId: 34,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/HFD_19791980-19911992_dark.svg',
  },
  {
    name: 'Atlanta Thrashers',
    teamColor: '#041E42',
    secondaryTeamColor: '#4B92DB',
    abbreviation: 'ATL',
    teamId: 11,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/ATL_19992000-20102011_dark.svg',
  },
  {
    name: 'Brooklyn Americans',
    teamColor: '#000000',
    secondaryTeamColor: '#CE1126',
    abbreviation: 'BRK',
    teamId: 51,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/BRK_19411942_dark.svg',
  },
  {
    name: 'Philadelphia Quakers',
    teamColor: '#CE1126',
    secondaryTeamColor: '#000000',
    abbreviation: 'QUA',
    teamId: 39,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/QUA_19301931_dark.svg',
  },
  {
    name: 'Hamilton Tigers',
    teamColor: '#000000',
    secondaryTeamColor: '#FFD100',
    abbreviation: 'HAM',
    teamId: 37,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/wchl/svg/CAT_19211922-19241925_dark.svg',
  },
  {
    name: 'Montreal Maroons',
    teamColor: '#76232F',
    secondaryTeamColor: '#A2AAAD',
    abbreviation: 'MMR',
    teamId: 43,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/MMR_19251926-19341935_dark.svg',
  },
  {
    name: 'New York Americans',
    teamColor: '#000000',
    secondaryTeamColor: '#CE1126',
    abbreviation: 'NYA',
    teamId: 44,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/NYA_19351936-19381939_dark.svg',
  },
  {
    name: 'Toronto St. Patricks',
    teamColor: '#0072CE',
    secondaryTeamColor: '#FFFFFF',
    abbreviation: 'TSP',
    teamId: 58,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/TSP_19191920-19211922_dark.svg',
  },
  {
    name: 'Toronto Arenas',
    teamColor: '#003087',
    secondaryTeamColor: '#FFFFFF',
    abbreviation: 'TAN',
    teamId: 57,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/TAN_19171918-19181919_dark.svg',
  },
  {
    name: 'Ottawa Senators (1917)',
    teamColor: '#000000',
    secondaryTeamColor: '#FF0000',
    abbreviation: 'SEN',
    teamId: 36,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/SEN_19171918-19331934_dark.svg',
  },
  {
    name: 'Minnesota North Stars',
    teamColor: '#009639',
    secondaryTeamColor: '#009639',
    abbreviation: 'MNS',
    teamId: 999999,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/MNS_19671968-19841985_light.svg',
  },
  {
    name: 'Montreal Wanderers',
    teamColor: '#000000',
    secondaryTeamColor: '#FF0000',
    abbreviation: 'MWN',
    teamId: 41,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/MWN_19171918_dark.svg',
  },
  {
    name: 'Quebec Bulldogs',
    teamColor: '#000000',
    secondaryTeamColor: '#FFFFFF',
    abbreviation: 'QBD',
    teamId: 42,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/QBD_19191920_dark.svg',
  },
  {
    name: 'Pittsburgh Pirates',
    teamColor: '#000000',
    secondaryTeamColor: '#FF0000',
    abbreviation: 'PIR',
    teamId: 38,
    division: 'Legacy',
    logo: 'https://assets.nhle.com/logos/nhl/svg/PIR_19251926-19271928_light.svg',
  },
  {
    name: 'Vancouver Millionaires',
    teamColor: '#6F263D',
    secondaryTeamColor: '#DDCBA4',
    abbreviation: 'VMI',
    teamId: 9999999,
    logo: 'https://assets.nhle.com/logos/pcha/svg/VMI_19141915-19221923_dark.svg',
  },
  {
    name: 'Vancouver Maroons',
    teamColor: '#6F263D',
    secondaryTeamColor: '#E5CB90',
    abbreviation: 'VMA',
    teamId: 9999999,
    logo: 'https://assets.nhle.com/logos/pcha/svg/VMA_19221923-19231924_light.svg',
  },
  {
    name: 'Victoria Cougars',
    teamColor: '#003087',
    secondaryTeamColor: '#FFFF00',
    abbreviation: 'VIC',
    teamId: 99999999,
    logo: 'https://assets.nhle.com/logos/wchl/svg/VIC_19221923-19251926_light.svg',
  },
  {
    name: 'Seattle Metropolitans',
    teamColor: '#154734',
    secondaryTeamColor: '#A6192E',
    abbreviation: 'SMT',
    teamId: 99999999,
    logo: 'https://assets.nhle.com/logos/pcha/svg/SMT_19151916-19231924_light.svg',
  },
];

// Sort teamData by .name
teamData.sort((a, b) => {
  const an = a.name || '';
  const bn = b.name || '';
  if (an < bn) {
    return -1;
  }
  if (an > bn) {
    return 1;
  }

  return 0;
});

const defaultTeam = (isHome: boolean): TeamDataEntry => {
  let teamColor = '#3A5DAE';
  let secondaryTeamColor = '#FFB81C';
  if (!isHome) {
    teamColor = '#FFB81C';
    secondaryTeamColor = '#3A5DAE';
  }

  return {
    name: 'NHL',
    hashtag: 'NHL',
    abbreviation: 'NHL',
    teamColor,
    secondaryTeamColor,
    teamId: 0,
  };
};

export const getTeamSlugs = (): (string | undefined)[] => {
  return (teamData as TeamDataEntry[]).map((team) => team.slug);
};

export const getTeamDataByAbbreviation = (abbreviation: string, isHome: boolean): TeamDataEntry => {
  const team = (teamData as TeamDataEntry[]).find((t) => t.abbreviation === abbreviation);

  return team ? team : defaultTeam(isHome);
};

export const getTeamDataByCommonName = (name: string, isHome: boolean): TeamDataEntry => {
  const team = (teamData as TeamDataEntry[]).find((t) => t.name === name);

  return team ? team : defaultTeam(isHome);
};

export const getTeamDataBySlug = (slug: string, isHome: boolean): TeamDataEntry => {
  const team = (teamData as TeamDataEntry[]).find(
    (t) => (t.name || '').toLowerCase().replace(' ', '-') === slug
  );

  return team ? team : defaultTeam(isHome);
};

export const getAllTeamsByDivision = (): Record<string, TeamDataEntry[]> => {
  const teams: Record<string, TeamDataEntry[]> = {
    Atlantic: [],
    Central: [],
    Metropolitan: [],
    Pacific: [],
  };

  (teamData as TeamDataEntry[]).forEach((team) => {
    if (!team.division || ['International', 'Legacy'].includes(team.division)) {
      return;
    }
    teams[team.division].push(team);
  });

  return teams;
};
