const teamData = [
  {
    name: 'Anaheim Ducks',
    hashtag: 'FlyTogether',
    abbreviation: 'ANA',
    teamColor: '#cf4520',
    secondaryTeamColor: '#89734c',
    teamId: 24,
  },
  {
    name: 'Boston Bruins',
    hashtag: 'NHLBruins',
    abbreviation: 'BOS',
    teamColor: '#FFB81C',
    secondaryTeamColor: '#000000',
    teamId: 6,
  },
  {
    name: 'Buffalo Sabres',
    hashtag: 'SabreHood',
    abbreviation: 'BUF',
    teamColor: '#003087',
    secondaryTeamColor: '#FFB81C',
    teamId: 7,
  },
  {
    name: 'Calgary Flames',
    hashtag: 'Flames',
    abbreviation: 'CGY',
    teamColor: '#c8102e',
    secondaryTeamColor: '#FAAF19',
    teamId: 20,
  },
  {
    name: 'Carolina Hurricanes',
    hashtag: 'RaiseUp',
    abbreviation: 'CAR',
    teamColor: '#c8102e',
    secondaryTeamColor: '#FFFFFF',
    teamId: 12,
  },
  {
    name: 'Chicago Blackhawks',
    hashtag: 'Blackhawks',
    abbreviation: 'CHI',
    teamColor: '#ce1126',
    secondaryTeamColor: '#FF671B',
    teamId: 16,
  },
  {
    name: 'Colorado Avalanche',
    hashtag: 'GoAvsGo',
    abbreviation: 'COL',
    teamColor: '#8a2432',
    secondaryTeamColor: '#236192',
    teamId: 21,
  },
  {
    name: 'Columbus Blue Jackets',
    hashtag: 'CBJ',
    abbreviation: 'CBJ',
    teamColor: '#041e42',
    secondaryTeamColor: '#ce1126',
    teamId: 29,
  },
  {
    name: 'Dallas Stars',
    hashtag: 'TexasHockey',
    abbreviation: 'DAL',
    teamColor: '#00823e',
    secondaryTeamColor: '#8F8F8C',
    teamId: 25,
  },
  {
    name: 'Detroit Red Wings',
    hashtag: 'LGRW',
    abbreviation: 'DET',
    teamColor: '#c8102e',
    secondaryTeamColor: '#FFFFFF',
    teamId: 17,
  },
  {
    name: 'Edmonton Oilers',
    hashtag: 'LetsGoOilers',
    abbreviation: 'EDM',
    teamColor: '#00205b',
    secondaryTeamColor: '#FF4C00',
    teamId: 22,
  },
  {
    name: 'Florida Panthers',
    hashtag: 'TimeToHunt',
    abbreviation: 'FLA',
    teamColor: '#041E42',
    secondaryTeamColor: '#c8102E',
    teamId: 13,
  },
  {
    name: 'Los Angeles Kings',
    hashtag: 'GoKingsGo',
    abbreviation: 'LAK',
    teamColor: '#8a9599',
    secondaryTeamColor: '#111111',
    teamId: 26,
  },
  {
    name: 'Minnesota Wild',
    hashtag: 'MNWild',
    abbreviation: 'MIN',
    teamColor: '#0e4431',
    secondaryTeamColor: '#ddc9a3',
    teamId: 30,
  },
  {
    name: 'Montréal Canadiens',
    hashtag: 'GoHabsGo',
    abbreviation: 'MTL',
    teamColor: '#a6192e',
    secondaryTeamColor: '#192168',
    teamId: 8,
  },
  {
    name: 'Nashville Predators',
    hashtag: 'Smashville',
    abbreviation: 'NSH',
    teamColor: '#ffb81c',
    secondaryTeamColor: '#041E42',
    teamId: 18,
  },
  {
    name: 'New Jersey Devils',
    hashtag: 'NJDevils',
    abbreviation: 'NJD',
    teamColor: '#cc0000',
    secondaryTeamColor: '#000000',
    teamId: 1,
  },
  {
    name: 'New York Islanders',
    hashtag: 'Isles',
    abbreviation: 'NYI',
    teamColor: '#00468b',
    secondaryTeamColor: '#f47d30',
    teamId: 2,
  },
  {
    name: 'New York Rangers',
    hashtag: 'NYR',
    abbreviation: 'NYR',
    teamColor: '#0033a0',
    secondaryTeamColor: '#CE1126',
    teamId: 3,
  },
  {
    name: 'Ottawa Senators',
    hashtag: 'GoSensGo',
    abbreviation: 'OTT',
    teamColor: '#c8102e',
    secondaryTeamColor: '#000000',
    teamId: 9,
  },
  {
    name: 'Philadelphia Flyers',
    hashtag: 'LetsGoFlyers',
    abbreviation: 'PHI',
    teamColor: '#d24303',
    secondaryTeamColor: '#000000',
    teamId: 4,
  },
  {
    name: 'Pittsburgh Penguins',
    hashtag: 'LetsGoPens',
    abbreviation: 'PIT',
    teamColor: '#000000',
    secondaryTeamColor: '#CFC493',
    teamId: 5,
  },
  {
    name: 'St. Louis Blues',
    hashtag: 'STLBlues',
    abbreviation: 'STL',
    teamColor: '#004986',
    secondaryTeamColor: '#FCB514',
    teamId: 19,
  },
  {
    name: 'San Jose Sharks',
    hashtag: 'TheFutureIsTeal',
    abbreviation: 'SJS',
    teamColor: '#00778b',
    secondaryTeamColor: '#e57200',
    teamId: 28,
  },
  {
    name: 'Seattle Kraken',
    hashtag: 'SeaKraken',
    abbreviation: 'SEA',
    teamColor: '#001425',
    secondaryTeamColor: '#99d9d9',
    teamId: 55,
  },
  {
    name: 'Tampa Bay Lightning',
    hashtag: 'GoBolts',
    abbreviation: 'TBL',
    teamColor: '#00205b',
    secondaryTeamColor: '#000',
    teamId: 14,
  },
  {
    name: 'Toronto Maple Leafs',
    hashtag: 'LeafsForever',
    abbreviation: 'TOR',
    teamColor: '#00205b',
    secondaryTeamColor: '#FFFFFF',
    teamId: 10,
  },
  {
    name: 'Utah Hockey Club',
    hashtag: 'UtahHC',
    abbreviation: 'UTA',
    teamColor: '#6cace4',
    secondaryTeamColor: '#010101',
    teamId: 59,
  },
  {
    name: 'Vancouver Canucks',
    hashtag: 'Canucks',
    abbreviation: 'VAN',
    teamColor: '#00205b',
    secondaryTeamColor: '#00843d',
    teamId: 23,
  },
  {
    name: 'Vegas Golden Knights',
    hashtag: 'VegasBorn',
    abbreviation: 'VGK',
    teamColor: '#b9975b',
    secondaryTeamColor: '#333f48',
    teamId: 54,
  },
  {
    name: 'Washington Capitals',
    hashtag: 'ALLCAPS',
    abbreviation: 'WSH',
    teamColor: '#041E42',
    secondaryTeamColor: '#C8102E',
    teamId: 15,
  },
  {
    name: 'Winnipeg Jets',
    hashtag: 'GoJetsGo',
    abbreviation: 'WPG',
    teamColor: '#041E42',
    secondaryTeamColor: '#004C97',
    teamId: 52,
  }
];

const defaultTeam = {
  'name': 'NHL',
  'hashtag': 'NHL',
  'abbreviation': 'NHL',
  'teamColor': '#010101',
  'teamId': 0,
};

export const getTeamDataByAbbreviation = (abbreviation) => {
  const team = teamData.find((t) => t.abbreviation === abbreviation);

  return team ? team : defaultTeam;
};

export const getTeamDataByCommonName = (name) => {
  const team = teamData.find((t) => t.name === name);

  return team ? team : defaultTeam;
};